project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index
        text: Home
      - text: Labs
        menu:
          - href: labs/lab_0/lab0_crouse.qmd
            text: "Lab 0: dplyr Basics"
          - href: labs/lab_1/lab1_crouse.qmd
            text: "Lab 1: Census Data Exploration"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto

