project:
  type: website
  output-dir: docs

navbar:
  left:
    - href: index.qmd
      text: Home
    - text: Labs
      menu:
        - href: labs/lab_0/lab0_crouse.html/
          text: "Lab 0: dplyr Basics"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
  